### ISSUE TITLE
Support pod restart on certificate renewal

### ISSUE THREAD

**Issue by omris94** [otterize/spire-integration-operator#45]
**Issue:** Some applications might not watch the secrets for updates. If the certificate expires it will cause a running application to  fail to communicate. Currently, users have to support it in their applications or use solutions like [wave](https://github.com/wave-k8s/wave).

Let's add support for configurable pod-restart on certificate renewal with annotation.

**Comment by usarid** [comment]
Sounds like a great idea. Would make the experience for some users less error prone and mysterious: why is authN failing when my certificate should be renewed? Let’s do it.

**Comment by orishoshan** [comment]
Proposal:

Add the proposed capability, and include global configuration to automatically enable the behavior for all pods which request Secrets that is enabled at the operator level, as well as configuration that is enabled using pod annotations, so a single workload can request this behavior.

Add a failsafe mechanism that prevents the restart from occurring if the pod started after the Secret was updated, or a similar mechanism which prevents the operator from repeatedly restarting pods due to a bug or unexpected interaction with another operator.

Upon Secret refresh, if:
1. global setting set by command line flag to always restart (delete) pods upon Secret refresh
2. pod annotation that requests that the operator restart (delete) the pod
3. the pod was not already restarted
then delete the pod.

**Comment by omris94** [comment]
Regarding the proposal, I think we should drop the global setting option. Two main reasons for that:
* Explicit is better than implicit - The person configuring the operator is not necessarily the person who is responsible for all the applications or their deployments. If it is going to be a global config, other users might experience unplanned/unexpected restarts.
* Keeping it simple - I think that at least at this stage, it is better to keep things simple. One way of doing something is better than two

@orishoshan, what do you say?

**Comment by orishoshan** [comment]
Sounds right - let's do it :)
